export const images = {
  search: "/assets/icons/search.svg",
  logo: "/assets/images/site-logo.svg",
  favicon: "/assets/favicon.svg",
  clock: "/assets/icons/clock.svg",
  dollar: "/assets/icons/currency-dollar-circle.svg",
  arrowUpRight: "/assets/icons/arrow-up-right.svg",
  stars: "/assets/icons/stars.svg",
  close: "/assets/icons/close.svg",
  location: "/assets/icons/carbon-location.svg",
  edit: "/assets/icons/edit.svg",
  trash: "/assets/icons/trash.svg",
  signIn: "/assets/icons/account.svg",
  signUp: "/assets/icons/sign-up.svg",
  logOut: "/assets/icons/logout.svg",
  lightIllustration: "/assets/images/light-illustration.png",
  darkIllustration: "/assets/images/dark-illustration.png",
  chevronRight: "/assets/icons/chevron-right.svg",
  hamburger: "/assets/icons/hamburger.svg",
};
